Traceback (most recent call last):
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from CoolProp import CoolProp as CP
###========== (a)================###
P = 0.8e6 # in Pa
u = 275 # in kJ/kg
fluid = "R134a"
uf = CP.PropsSI("U", "Q", 0, "P", P,fluid)/1e3
ug = CP.PropsSI("U", "Q", 1, "P", P, fluid)/1e3
print("Uf at given pressure: {} kJ/kg".format(round(uf,1)))
print("Ug at given pressure: {} kJ/kg".format(round(ug,1)))
## we are in saturated mixture region; since u_given > uf and u_given < ug!
T = CP.PropsSI("T","P",P,"Q",0,fluid)
print("Phase description: Saturated mixture")
print("Temperature: {}".format(round(T - 273.15,2)),"deg C")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mCoolProp[39;00m [38;5;28;01mimport[39;00m CoolProp [38;5;28;01mas[39;00m CP
[0;32m      2[0m [38;5;66;03m###========== (a)================###[39;00m
[0;32m      3[0m P [38;5;241m=[39m [38;5;241m0.8e6[39m [38;5;66;03m# in Pa[39;00m

[1;31mModuleNotFoundError[0m: No module named 'CoolProp'

